"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['EmulatorManagerMacOS.py']
APP_NAME = "EmulatorManagerMacOS"
DATA_FILES = []
OPTIONS = {'argv_emulation': True,
           'iconfile': 'icon.icns',
           'plist': {
                    'CFBundleName': APP_NAME,
                    'CFBundleDisplayName': APP_NAME,
                    'CFBundleGetInfoString': "Emulator Manager",
                    'CFBundleIdentifier': "com.metachris.osx.EmulatorManagerApp",
                    'CFBundleVersion': "0.1.0",
                    'CFBundleShortVersionString': "0.1.0",
                    'NSHumanReadableCopyright': u"Copyright © 2020, Tomas Matos, All Rights Reserved"
                }
           }

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
